In [2]:
from bs4 import BeautifulSoup
import pandas as pd
import requests

In [8]:
url = 'https://kairosoft.fandom.com/wiki/Special_Rooms_(Dream_House_Days)'
page = requests.get(url)
soup = BeautifulSoup(page.text,'html')
table = soup.find('table', class_ = "wikitable oddrow sortable")

In [31]:
table_header = table.find_all('th')
table_header = [header.text.strip() for header in table_header]
dhd_special_room = pd.DataFrame(columns=table_header)

In [32]:
table_data = table.find_all('tr')
for data_row in table_data[1:]:
    data_row = data_row.find_all('td')
    entry = [data.text.strip() if data.text.strip()!='∅' else '' for data in data_row ]
    
    curr_len = len(dhd_special_room)
    dhd_special_room.loc[curr_len] = entry
    
dhd_special_room

,Name,Item 1,Item 2,Floor,Rent,Comf.,In,Fi,Ho,Ch
0,Bedroom,Bed,Lamp or Floor Lamp,Cushion Flooring,+0.2K,+3,+,+,+,+
1,Chic Bedroom,Chic Bed,Aquarium,Carpet,+0.6K,+8,+,+,+,+
2,Gaudy Bedroom,Pink Bed,Heart Rug,Pink Floor,+0.7K,+9,+,+,+,+
3,Kids' Room,Crib,Space Robot,Green Floor,+0.6K,+8,+,+,+,+
4,Modern Kitchen A,Cupboard,Refrigerator,Orange Floor,,+8,,+,,
...,...,...,...,...,...,...,...,...,...,...
65,Bathhouse,Cypress Bath,Whirlpool Bath,Tile,+0.2K,+3,,+,,
66,Steaming Room,Whirlpool Bath,Sauna,Tile,+0.4K,+5,,+,,
67,Sauna Room,Sauna,Shower,Tile,+0.3K,+4,+,+,+,+
68,Leisure Room,Karaoke Room,Juice Bar,Carpet,+0.7K,+9,,,+,
69,Elegant Garden,Pond,Flower Vase or Plant or Flower Bed,,+0.3K,+4,,,,

In [36]:
df1 = dhd_special_room.query("Floor == 'Cushion Flooring'")
df1

,Name,Item 1,Item 2,Floor,Rent,Comf.,In,Fi,Ho,Ch
0,Bedroom,Bed,Lamp or Floor Lamp,Cushion Flooring,+0.2K,+3,+,+,+,+
35,Storage Room,Storage Rack,Wardrobe or Closet,Cushion Flooring,+0.5K,+6,,,,+
37,Breezy Room,Fan,[Any] Curtains,Cushion Flooring,,+2,,,+,
58,Classic Storage,Closet,Bureau,Cushion Flooring,+0.6K,+7,,+,,